# Generated by Django 2.1.3 on 2018-11-07 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mood_entry', models.CharField(max_length=400)),
                ('mood_rating', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7')], max_length=1)),
                ('mood_date', models.DateField()),
            ],
            options={
                'ordering': ['-mood_date'],
            },
        ),
    ]
