# Generated by Django 2.1 on 2018-09-19 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moodjournal', '0004_auto_20180918_2325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journalentry',
            name='mood_date',
        ),
    ]
