# Generated by Django 2.1 on 2018-09-26 04:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('moodjournal', '0005_remove_journalentry_mood_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='mood_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
